### PR TITLE
Fix build with Nettle 4 by using version macros

### LINKED ISSUE #196: gtkhash 1.5 build error against nettle 4
gtkhash 1.5 FTBFS against nettle 4 with
```
hash-lib-nettle.c: In function 'gtkhash_hash_lib_nettle_finish':
hash-lib-nettle.c:106:47: error: passing argument 2 of '((struct hash_lib_nettle_s *)func->lib_data)->meta->digest' makes pointer from integer without a cast [-Wint-conversion]
  106 |         LIB_DATA->meta->digest(LIB_DATA->ctx, *size, digest);
      |                                               ^~~~~
      |                                               |
      |                                               size_t {aka long unsigned int}
hash-lib-nettle.c:106:47: note: expected 'uint8_t *' {aka 'unsigned char *'} but argument is of type 'size_t' {aka 'long unsigned int'}
hash-lib-nettle.c:36:19: error: too many arguments to function '((struct hash_lib_nettle_s *)func->lib_data)->meta->digest'; expected 2, have 3
```

### PR DESCRIPTION
**Pull request by megvadulthangya**
Nettle 4 changed the digest function signature, removing the length parameter. Add an include for nettle/version.h and use NETTLE_VERSION_MAJOR to conditionally compile the correct call, ensuring compatibility with both Nettle 3.x and 4.x.

This resolves build failures on systems where Nettle 4 is the default (e.g., recent Manjaro).

### CODE REVIEW

**Comment by megvadulthangya** [comment]
Update: I've tested this patch via a GitHub Actions builder targeting Manjaro Stable (which recently moved to Nettle 4.0). The package builds without errors, and the resulting gtkhash-thunar extension has been verified to work perfectly on an AwesomeWM setup.

**Comment by LFd3v** [comment]
Hi, there. I have applied this [patch](https://github.com/gtkhash/gtkhash/pull/199.patch) to the AUR package `gtkhash-nemo 1.5-3` and it builds fine with `nettle 4.0-1`, and both gtkhash app and the nemo plugin work fine.

@megvadulthangya Thank you for the patch.

Regards

**Comment by megvadulthangya** [comment]
Awesome, thanks for testing it with the Nemo extension and verifying it on your end! This confirms the macro fix works seamlessly across different plugin targets too. Appreciate the feedback! 🚀

**Comment by LFd3v** [comment]
Update: it seems that Arch provides `nettle3` as well, it can be installed together with regular `nettle` (4.x version) with no conflict. I tested the build with this patch while `nettle3` is installed and build, gtkhash app and nemo plugin all worked fine for me. So the patch seems to be backward compatible as well.

**Comment by megvadulthangya** [comment]
Exactly, nettle 4.x is the default now on Arch/Manjaro, which is why the build broke in the first place.

Thank you so much for testing the backward compatibility with the nettle3 package as well! This is great news, as it proves the patch safely unifies both worlds without breaking older setups.

**Review by tristanheaven — APPROVED** [review]

**Comment by tristanheaven** [comment]
Looks good, thanks.

CI needs to be fixed to catch issues like this. Probably using GitHub Actions as GitLab/Travis isn't working now.

**Comment by megvadulthangya** [comment]
Yeah, a Linux matrix build under GitHub Actions (testing both stable and rolling releases) would definitely catch these toolchain and library upgrades earlier.

Thanks for merging the fix, glad I could help! Good luck with the CI refactoring.
